version: '3.8'
services:
  vite-app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify your Dockerfile name if different
    ports:
      - "6969:5173"  # Maps host port 6969 to container port 5173